// templates/frontend/vue/src/App.vue
<script setup>
import { ref } from 'vue';

const count = ref(0);
const projectName = '{{projectName}}';
</script>

<template>
  <div class="app">
    <header class="app-header">
      <h1>Welcome to {{ projectName }}</h1>
      <p>Built with Vue + Vite 💚</p>

      <div class="card">
        <button @click="count++">Count is {{ count }}</button>
        <p>Edit <code>src/App.vue</code> and save to test HMR</p>
      </div>

      <p class="read-the-docs">Click on the Vite and Vue logos to learn more</p>

      <footer class="footer">
        Built by
        <a href="https://harib.vercel.app" target="_blank" rel="noopener">hariswarreddy</a>
      </footer>
    </header>
  </div>
</template>

<style scoped>
.app {
  max-width: 1280px;
  margin: 0 auto;
  padding: 2rem;
  text-align: center;
}

.app-header {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  min-height: 100vh;
}

h1 {
  font-size: 3.2em;
  line-height: 1.1;
  background: linear-gradient(135deg, #fafafa 0%, #71717a 100%);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}

.card {
  padding: 2em;
}

button {
  border-radius: 8px;
  border: 1px solid #27272a;
  padding: 0.6em 1.2em;
  font-size: 1em;
  font-weight: 500;
  font-family: inherit;
  background-color: #18181b;
  color: #fafafa;
  cursor: pointer;
  transition: all 0.25s ease;
}

button:hover {
  background-color: #27272a;
  border-color: #3f3f46;
  transform: scale(1.05);
}

.read-the-docs {
  color: #71717a;
}

code {
  background: #27272a;
  padding: 0.2em 0.4em;
  border-radius: 4px;
  font-size: 0.9em;
}
</style>

// templates/frontend/react/src/App.jsx
import { useState } from 'react';
import './App.css';

function App() {
  const [count, setCount] = useState(0);

  return (
    <div className="app">
      <header className="app-header">
        <h1>Welcome to {{projectName}}</h1>
        <p>Built with React + Vite ⚡</p>
        
        <div className="card">
          <button onClick={() => setCount((count) => count + 1)}>
            Count is {count}
          </button>
          <p>
            Edit <code>src/App.jsx</code> and save to test HMR
          </p>
        </div>
        
        <p className="read-the-docs">
          Click on the Vite and React logos to learn more
        </p>
        
        <footer className="footer">
          Built by <a href="https://harib.vercel.app" target="_blank" rel="noopener noreferrer">hariswarreddy</a>
        </footer>
      </header>
    </div>
  );
}

export default App;
