// templates/frontend/vue/src/App.vue
<script setup>
import { ref } from 'vue';

const count = ref(0);
const projectName = '{{projectName}}';
</script>

<template>
  <div class="app">
    <header class="app-header">
      <h1>Welcome to {{ projectName }}</h1>
      <p>Built with Vue + Vite 💚</p>

      <div class="card">
        <button @click="count++">Count is {{ count }}</button>
        <p>Edit <code>src/App.vue</code> and save to test HMR</p>
      </div>

      <p class="read-the-docs">Click on the Vite and Vue logos to learn more</p>

      <footer class="footer">
        Built by
        <a href="https://harib.vercel.app" target="_blank" rel="noopener">hariswarreddy</a>
      </footer>
    </header>
  </div>
</template>

<style scoped>
.app {
  max-width: 1280px;
  margin: 0 auto;
  padding: 2rem;
  text-align: center;
}

.app-header {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  min-height: 100vh;
}

h1 {
  font-size: 3.2em;
  line-height: 1.1;
  background: linear-gradient(135deg, #fafafa 0%, #71717a 100%);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  background-clip: text;
}

.card {
  padding: 2em;
}

button {
  border-radius: 8px;
  border: 1px solid #27272a;
  padding: 0.6em 1.2em;
  font-size: 1em;
  font-weight: 500;
  font-family: inherit;
  background-color: #18181b;
  color: #fafafa;
  cursor: pointer;
  transition: all 0.25s ease;
}

button:hover {
  background-color: #27272a;
  border-color: #3f3f46;
  transform: scale(1.05);
}

.read-the-docs {
  color: #71717a;
}

code {
  background: #27272a;
  padding: 0.2em 0.4em;
  border-radius: 4px;
  font-size: 0.9em;
}
</style>

// templates/frontend/react-tailwind/src/App.jsx
import { useState } from 'react';

function App() {
  const [count, setCount] = useState(0);

  return (
    <div className="min-h-screen bg-zinc-950 flex items-center justify-center">
      <div className="text-center">
        <h1 className="text-5xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-white via-zinc-400 to-zinc-600 mb-4">
          Welcome to {'{{projectName}}'}
        </h1>
        <p className="text-zinc-400 text-xl mb-8">
          Built with React + Vite + Tailwind CSS ⚡
        </p>
        
        <div className="bg-zinc-900/50 backdrop-blur-lg rounded-2xl p-8 border border-zinc-800 shadow-2xl">
          <button
            onClick={() => setCount((count) => count + 1)}
            className="px-8 py-4 bg-white text-zinc-950 font-semibold rounded-xl 
                       hover:bg-zinc-200 transform hover:scale-105 transition-all duration-300
                       shadow-lg"
          >
            Count is {count}
          </button>
          <p className="mt-6 text-zinc-500">
            Edit <code className="bg-zinc-800 px-2 py-1 rounded text-zinc-300">src/App.jsx</code> and save to test HMR
          </p>
        </div>

        <p className="mt-8 text-zinc-600">
          Click on the Vite and React logos to learn more
        </p>

        <footer className="mt-12 text-zinc-700 text-sm">
          Built by <a href="https://harib.vercel.app" target="_blank" rel="noopener noreferrer" className="text-zinc-500 hover:text-white transition-colors">hariswarreddy</a>
        </footer>
      </div>
    </div>
  );
}

export default App;
